var GAME_LEVELS = [
  ["                                                                                ",
   "xxxxxxxx   xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "        x x          x x                       x x                              ",
   "         x            x                         x                               ",
   "         v            v                         v                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                         o               o                     oo               ",
   "  @                       o               o                  xxxxxx  oo         ",
   "xxxx!!!xxxxxxxx!!!!!!xxxxxxxxxx!!!!!!xxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                        x        x                                         ",
   "                                        xx     0 x                                         ",
   "                                        x      x x                                         ",
   "                                        x       xxxxxxxxxxx                                ",
   "                                        xx                                                 ",
   "                                        x                                                  ",
   "                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   " @ x  y                            xx                                                      ",
   "xxxx!!!!xx!!xx!!!xxxx!!!!!!!xx!!!!x                                                        ",
   "xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       =           x =             x=            x     ",
   "xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx    xxxxxxx      xxxxxxxxx    xxxxxxxxxxxxxxx",
   "                                             x    x     x      x       x    x              ",
   "                                             xxxxxx     xxxxxxxx       xxxxxx              ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           "],
  ["  xx                                                                                                          ",
   "  xx                                                                                                          ",
   "  xx                                                                                                          ",
   "  xx                                                                                                          ",
   "  xx                                                                                                          ",
   "  xx                                                                                                          ",
   "  xx                                                                                  o                       ",
   "  xx     @       xx  xx xx    y    xx    xx     xx    xx y     xx    xx       x     xxxxx                     ",
   "  xx     xx       xx         xx              xx         xx        xx         xx      xx                       ",
   "  xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!             ",
   "  xx                                                                                                          ",
   "  xx                                                                                                          ",
   "  xx                                                                                                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
